config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users do
    resources :expenses, only: [:new, :create], controller: 'users/expenses'
    resources :incomes, only: [:new, :create], controller: 'users/incomes'
    member do
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/transactionable.rb
module Transactionable
  extend ActiveSupport::Concern
  include ActiveModel::Validations

  included do
    validates :amount, presence: true, numericality: { greater_than: 0 }
    validates :transaction_time, presence: true
    validates :user, presence: true

    scope :in_month, -> { where('transaction_time > ? AND transaction_time < ?', (Date.today).beginning_of_month, (Date.today + 1.month).beginning_of_month) }
    scope :commited, -> { where('transaction_time <= ?', Time.now) }
  end
end

app/models/expense.rb
class Expense < ApplicationRecord
  include Transactionable

  belongs_to :user, inverse_of: :expenses
end

app/models/income.rb
class Income < ApplicationRecord
  include Transactionable

  belongs_to :user, inverse_of: :incomes
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 20 }, allow_blank: false
  validates :birthday, presence: true
  validate :birthday_is_in_past

  has_many :incomes, inverse_of: :user, dependent: :destroy
  has_many :expenses, inverse_of: :user, dependent: :destroy

  before_validation :strip_name_strings, on: [:create, :update]

  def age
    y = TimeHandler.get_difference_in_years(self.birthday)
    "#{ y } #{ TimeHandler.get_russian_years(y) }"
  end

  def in_month_transactions
    incomes = self.incomes.in_month
    expenses = self.expenses.in_month
    transactions = (incomes + expenses) rescue nil
  end

  def get_month_balance
    transactions = self.in_month_transactions
    (return 0) unless transactions.present?
    transactions.map { |t| (t.kind_of?(Income) ? t.amount : -t.amount) }.sum()
  end

  private
  # Альтернатива - сделать кастомный валидатор для временнЫх величин в app/validators/
  def birthday_is_in_past
    if birthday.present? && birthday >= Date.today
      errors.add(:birthday, "Нельзя зарегистрировать еще не родившегося пользователя!")
    end
  end

  # Не допускаем пробелы в конце и начале name.
  def strip_name_strings
    if self.changes[:name].present?
      self.name.strip!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users/expenses_controller.rb
class Users::ExpensesController < ApplicationController
  def new
    @user = User.find params[:user_id]
    @expense = @user.expenses.new
  end

  def create
    @user = User.find params[:user_id]
    @expense = @user.expenses.new
    amount = BigDecimal(expense_params[:amount]) rescue nil
    purpose = expense_params[:purpose] rescue ''
    user_id = params[:user_id].to_i rescue nil
    transaction_time = expense_params[:transaction_time].to_datetime.to_s rescue nil
    if amount.present? && user_id.present? && transaction_time.present?
      sql = "SELECT create_expense(#{ amount }, #{ user_id }, '#{ transaction_time }', '#{ purpose }');"
      records_array = ActiveRecord::Base.connection.execute(sql)
      flash.notice = 'Информация о расходе денежных средств зарегистрирована.'
      redirect_to user_path(params[:user_id])
    else
      flash.alert = 'Исправьте ошибки'
      render :new
    end
  end

  private
  def expense_params
    params.require(:expense).permit(
      :amount,
      :transaction_time,
      :user_id,
      :purpose,
    )
  end
end

app/controllers/users/incomes_controller.rb
class Users::IncomesController < ApplicationController
  def new
    @user = User.find params[:user_id]
    @income = @user.incomes.new
  end

  def create
    @user = User.find params[:user_id]
    @income = @user.incomes.new
    amount = BigDecimal(income_params[:amount]) rescue nil
    user_id = params[:user_id].to_i rescue nil
    transaction_time = income_params[:transaction_time].to_datetime.to_s rescue nil
    if amount.present? && user_id.present? && transaction_time.present?
      sql = "SELECT create_income(#{ amount }, #{ user_id }, '#{ transaction_time }');"
      records_array = ActiveRecord::Base.connection.execute(sql)
      flash.notice = 'Информация о поступлении денежных средств зарегистрирована.'
      redirect_to user_path(params[:user_id])
    else
      flash.alert = 'Исправьте ошибки'
      render :new
    end
  end

  private
  def income_params
    params.require(:income).permit(
      :amount,
      :transaction_time,
      :user_id,
    )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find params[:id]
    @transactions = @user.in_month_transactions
  end

  def index
    @users = User.all.order(:name)
    service = GetInfoForUserIndex.new(params)
    @balances_hash = service.get_balances_hash
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash.notice = 'Пользователь добавлен'
      redirect_to root_path
    else
      flash.alert = 'Исправьте ошибки'
      render :new
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update(user_params)
      flash.notice = 'Информация о пользователе отредактирована'
      redirect_to root_path
    else
      flash.alert = 'Исправьте ошибки'
      render :edit
    end
  end

  def destroy
    @user = User.find params[:id]
    if @user.destroy
      flash.notice = 'Пользователь удален!'
    else
      flash.alert = "Пользователь не был удален!"
    end
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(
      :name,
      :birthday,
      :address,
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content="text/html; charset=UTF-8" http-equiv="Content-Type"
    meta charset="UTF-8"
    meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"
    title BALANCE || #{ yield(:seo_title).present? ? yield(:seo_title) : 'Приложение для расчета баланса.'}
    meta name="description" content="#{ yield(:seo_description) }"
    meta name="keywords" content="#{ yield(:seo_keys) }"
    / link rel="icon" href=asset_path("favicon.ico")
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    = render 'layouts/partials/loader'
    - ['alert', 'notice'].each do |fl|
      - if flash.send(fl).present?
        #flash-alert class="flash_color_#{ fl }" = flash.send(fl)
    header
      .container-fluid
        .header
          = render 'layouts/partials/header'
    .content-wrapper
      .row
        .col-sm-6.col-sm-offset-3.col-xs-10.col-xs-offset-1
          = yield

app/views/layouts/partials/_footer.html.slim
#footer
  span#first-footer-span.padding-right-30 Kurilka © 2019
  span
    |Built by 
    a.underline-border href='https://vk.com/aleko_spb' target='blank' Alexey Kozenko
  div#scroll-to-top-button

app/views/layouts/partials/_header.html.slim
.row#header
  .col-sm-4.col-sm-offset-4.text-center
    = link_to root_path
      h2.margin-top-0.margin-bottom-0 Balance

app/views/layouts/partials/_loader.html.slim
#loading-state-div
  div.spinner-container
    #logo-loader
      #logo-loader-text
        |B
        span#xs-logo-loader-little alance
      br
      i.fa.fa-spinner.fa-pulse.fa-5x.fa-fw
        span.sr-only

app/views/users/_form.html.slim
= simple_form_for @user, html: { class: 'form-horizontal' } do |f|
  .row.text-center
    .col-sm-4
      = f.input :name
    .col-sm-4
      = f.input :birthday, as: :string, input_html: { class: 'datepicker', value: (@user.birthday.present? ? TimeHandler.rus_date(@user.birthday) : nil) }
    .col-sm-4
      = f.input :address
  .row
    .col-sm-12.text-center.margin-top-100.margin-bottom-40
      = f.submit 'Сохранить', class: 'btn btn-lg btn-default flat'

app/views/users/_quote_block.html.slim
.quote__block data-quote-id="#{ quote.id }"
  .quote__header
    .quote__header_author = quote.author_nickname
    .quote__header_date = rus_dtime quote.created_at
  .quote__body.whitespacer
    = quote.text
  .quote__footer
    .text-center.full-width
      = link_to 'javascript:void(0);', class: 'rate_toggler', data: { direction: 'down' }
        i.fa.fa-thumbs-down.margin-right-30
      span.quote__footer_counter = quote.rate
      = link_to 'javascript:void(0);', class: 'rate_toggler', data: { direction: 'up' }
        i.fa.fa-thumbs-up.margin-left-30

app/views/users/_user_transactions_table.html.slim
.row
  .col-sm-12.text-center
    h3 Транзакции пользователя за месяц:
    table#transactions_table.table.table-borderless
      thead
        tr
          th
            = link_to new_user_income_path(@user)
              i.fa.fa-plus
          th
            = link_to new_user_expense_path(@user)
              i.fa.fa-minus
      tbody
        - for date, transactions_in_date in @transactions.group_by { |t| t[:transaction_time].to_date }.sort_by { |k, v| k }.reverse do
          tr.date-row
            td.text-center colspan='2'
              span.label.label-default.flat = TimeHandler.rus_date date
          - for transaction in transactions_in_date.sort_by { |t| t[:transaction_time] }.reverse
            tr
              - if transaction.kind_of?(Income)
                td
                  p
                    small.text-muted = TimeHandler.rus_time transaction.transaction_time
                  p = CurrencyHandler.ntc(transaction.amount)
                td
              - else
                td
                td
                  p
                    small.text-muted
                      = TimeHandler.rus_time transaction.transaction_time
                      - unless transaction.purpose.blank?
                        |: #{ transaction.purpose }
                  p = CurrencyHandler.ntc(transaction.amount)
      tfoot
        tr#balance-row
          td colspan='2'
            |Итоговый баланс: #{ CurrencyHandler.ntc(@transactions.map { |t| (t.kind_of?(Income) ? t.amount : -t.amount) }.sum()) }

app/views/users/edit.html.slim
= content_for :seo_title
  | Редактировать информацию о пользователе

= content_for :seo_description
  | Balance. Редактировать информацию о пользователе

= render 'form'

app/views/users/expenses/new.html.slim
= content_for :seo_title
  | Регистрация расхода денежных средств

= content_for :seo_description
  | Balance. Регистрация расхода денежных средств пользователя #{ @user.name }

= simple_form_for [@user, @expense] do |f|
  .row.text-center
    .col-sm-4
      = f.input :amount
    .col-sm-4
      = f.input :transaction_time, as: :string, input_html: { class: 'datetimepicker' }
    .col-sm-4
      = f.input :purpose
  .row
    .col-sm-12.text-center.margin-top-100.margin-bottom-40
      = f.submit 'Сохранить', class: 'btn btn-lg btn-default flat'

app/views/users/incomes/new.html.slim
= content_for :seo_title
  | Регистрация поступления денежных средств

= content_for :seo_description
  | Balance. Регистрация поступления денежных средств пользователя #{ @user.name }

= simple_form_for [@user, @income] do |f|
  .row.text-center
    .col-sm-6
      = f.input :amount
    .col-sm-6
      = f.input :transaction_time, as: :string, input_html: { class: 'datetimepicker' }
  .row
    .col-sm-12.text-center.margin-top-100.margin-bottom-40
      = f.submit 'Сохранить', class: 'btn btn-lg btn-default flat'

app/views/users/index.html.slim
= content_for :seo_title
  | Главная

= content_for :seo_description
  | Balance - Приложение для расчета баланса

.row
  .col-sm-12
    .full-width.text-right
      = link_to new_user_path, class: 'btn btn-default btn-sm flat margin-bottom-30'
        i.fa.fa-plus.margin-right-5
        |Добавить пользователя
    table.table.table-bordered
      thead
        tr
          th #
          th Имя
          th Возраст
          th Адрес
          th Баланс
          th Управление
      tbody
        - @users.each_with_index do |user, i|
          tr
            td = i + 1
            td = user.name
            td = user.age
            td = user.address
            td.text-center
              .pull-left
                = link_to new_user_income_path(user.id), title: 'Регистрация поступления денежных средств', class: 'btn btn-success btn-xs flat margin-right-5'
                  i.fa.fa-plus
              span.w100px = CurrencyHandler.ntc @balances_hash[user.id] || '0'
              .pull-right
                = link_to new_user_expense_path(user.id), title: 'Регистрация поступления денежных средств', class: 'btn btn-danger btn-xs flat margin-left-5'
                  i.fa.fa-minus
            td.text-center
              = link_to user_path(user.id), title: 'Просмотр информации о пользователе', class: 'btn btn-default btn-xs flat margin-right-5'
                i.fa.fa-eye
              = link_to edit_user_path(user.id), title: 'Редактировать информацию о пользователе', class: 'btn btn-default btn-xs flat margin-right-5'
                i.fa.fa-pencil
              = link_to user_path(user), method: :delete, title: 'Удалить пользователя', class: 'btn flat btn-xs btn-danger', data: { confirm: "Уверены, что хотите удалить пользователя #{ user.name }?" }
                i.fa.fa-trash

app/views/users/new.html.slim
= content_for :seo_title
  | Новый пользователь

= content_for :seo_description
  | Balance. Добавить нового пользователя

= render 'form'

app/views/users/show.html.slim
= content_for :seo_title
  | Пользователь #{  @user.name }

= content_for :seo_description
  | Balance. Пользователь

.row
  .col-sm-12.text-center
    h3 Информация о пользователе #{ @user.name }
    .text-muted
      |Возраст #{ @user.age }.
      - unless @user.address.blank?
      |&nbsp;Адрес: #{ @user.address }.
- if @transactions.present?
  = render 'user_transactions_table'

.row
  .col-sm-12.text-center.margin-top-40.margin-bottom-40
    = link_to 'Назад к списку пользователей', root_path, class: 'btn btn-default btn-sm flat'